class Canvas:
    def __init__(self: Canvas, width: int, height: int) -> None: ...

    def set_pixel(self: Canvas, x: int, y: int, color: tuple[int, int, int, int]) -> None: ...
    def get_pixel(self: Canvas, x: int, y: int) -> tuple[int, int, int, int]: ...
    def resize(self: Canvas, width: int, height: int, resize_canvas_contents: bool = False, smooth_resize: bool = False) -> None: ...
    def copy_content(self: Canvas, target: Canvas) -> None: ...
    def draw_line(self: Canvas, x0: int, y0: int, x1: int, y1: int, color: tuple[int, int, int, int]) -> None: ...
    def fill(self: Canvas, x: int, y: int, color: tuple[int, int, int, int]) -> None: ...
    def clear(self: Canvas) -> None: ...
    def clone(self: Canvas) -> Canvas: ...


def render_canvases(width: int, height: int, canvases: list[Canvas], alpha_blendings: list[int], highlight_x: int = -1, highlight_y: int = -1) -> bytes: ...
