# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewFileWindow(object):
    def setupUi(self, NewFileWindow):
        NewFileWindow.setObjectName("NewFileWindow")
        NewFileWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        NewFileWindow.resize(380, 122)
        NewFileWindow.setStyleSheet("QWidget {\n"
"    background: rgb(51, 51, 51);\n"
"    color: white;\n"
"}\n"
"\n"
"QSpinBox {\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 2px 5px;\n"
"    background: #555;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    background: #555;\n"
"    color: white;\n"
"}")
        self.label = QtWidgets.QLabel(NewFileWindow)
        self.label.setGeometry(QtCore.QRect(10, 35, 51, 21))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(NewFileWindow)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 51, 16))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.widthBox = QtWidgets.QSpinBox(NewFileWindow)
        self.widthBox.setGeometry(QtCore.QRect(70, 7, 71, 21))
        self.widthBox.setStyleSheet("")
        self.widthBox.setWrapping(False)
        self.widthBox.setFrame(True)
        self.widthBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.widthBox.setAccelerated(False)
        self.widthBox.setMinimum(1)
        self.widthBox.setMaximum(4096)
        self.widthBox.setProperty("value", 32)
        self.widthBox.setObjectName("widthBox")
        self.heightBox = QtWidgets.QSpinBox(NewFileWindow)
        self.heightBox.setGeometry(QtCore.QRect(70, 35, 71, 22))
        self.heightBox.setStyleSheet("")
        self.heightBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.heightBox.setMinimum(1)
        self.heightBox.setMaximum(4096)
        self.heightBox.setProperty("value", 32)
        self.heightBox.setObjectName("heightBox")
        self.keepAspectRatioCheckbox = QtWidgets.QCheckBox(NewFileWindow)
        self.keepAspectRatioCheckbox.setGeometry(QtCore.QRect(150, 23, 191, 20))
        self.keepAspectRatioCheckbox.setObjectName("keepAspectRatioCheckbox")
        self.okButton = QtWidgets.QPushButton(NewFileWindow)
        self.okButton.setGeometry(QtCore.QRect(290, 90, 80, 22))
        self.okButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.okButton.setStyleSheet("")
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(NewFileWindow)
        self.cancelButton.setGeometry(QtCore.QRect(200, 90, 80, 22))
        self.cancelButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(NewFileWindow)
        QtCore.QMetaObject.connectSlotsByName(NewFileWindow)

    def retranslateUi(self, NewFileWindow):
        _translate = QtCore.QCoreApplication.translate
        NewFileWindow.setWindowTitle(_translate("NewFileWindow", "SettingsWindow"))
        self.label.setText(_translate("NewFileWindow", "Высота:"))
        self.label_2.setText(_translate("NewFileWindow", "Ширина:"))
        self.keepAspectRatioCheckbox.setText(_translate("NewFileWindow", "Сохранять соотношение сторон"))
        self.okButton.setText(_translate("NewFileWindow", "OK"))
        self.cancelButton.setText(_translate("NewFileWindow", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewFileWindow = QtWidgets.QWidget()
    ui = Ui_NewFileWindow()
    ui.setupUi(NewFileWindow)
    NewFileWindow.show()
    sys.exit(app.exec_())
