# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(800, 525)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(400, 525))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background: #ccc;")
        self.brushPanel = QtWidgets.QGroupBox(MainWindow)
        self.brushPanel.setGeometry(QtCore.QRect(0, 25, 115, 500))
        self.brushPanel.setMinimumSize(QtCore.QSize(115, 0))
        self.brushPanel.setMaximumSize(QtCore.QSize(115, 16777215))
        self.brushPanel.setAutoFillBackground(False)
        self.brushPanel.setStyleSheet("QGroupBox {\n"
                                      "    background: #333;\n"
                                      "    border: none;\n"
                                      "    border-top-right-radius: 10px;\n"
                                      "    border-bottom-right-radius: 10px;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton {\n"
                                      "    background: #999;\n"
                                      "    border: none;\n"
                                      "    border-radius: 5px;\n"
                                      "}")
        self.brushPanel.setTitle("")
        self.brushPanel.setFlat(True)
        self.brushPanel.setCheckable(False)
        self.brushPanel.setObjectName("brushPanel")
        self.penButton = QtWidgets.QPushButton(self.brushPanel)
        self.penButton.setGeometry(QtCore.QRect(10, 10, 42, 42))
        self.penButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.penButton.setStyleSheet("QPushButton {\n"
                                     "    background: #ff00ae;\n"
                                     "}")
        self.penButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/icons/pen.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.penButton.setIcon(icon)
        self.penButton.setIconSize(QtCore.QSize(24, 24))
        self.penButton.setFlat(False)
        self.penButton.setObjectName("penButton")
        self.strokeButton = QtWidgets.QPushButton(self.brushPanel)
        self.strokeButton.setGeometry(QtCore.QRect(60, 10, 42, 42))
        self.strokeButton.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.strokeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/icons/stroke.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.strokeButton.setIcon(icon1)
        self.strokeButton.setIconSize(QtCore.QSize(24, 24))
        self.strokeButton.setObjectName("strokeButton")
        self.pickerButton = QtWidgets.QPushButton(self.brushPanel)
        self.pickerButton.setGeometry(QtCore.QRect(10, 60, 42, 42))
        self.pickerButton.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pickerButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/icons/picker.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pickerButton.setIcon(icon2)
        self.pickerButton.setIconSize(QtCore.QSize(24, 24))
        self.pickerButton.setObjectName("pickerButton")
        self.fillButton = QtWidgets.QPushButton(self.brushPanel)
        self.fillButton.setGeometry(QtCore.QRect(60, 60, 42, 42))
        self.fillButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fillButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("assets/icons/fill.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fillButton.setIcon(icon3)
        self.fillButton.setIconSize(QtCore.QSize(24, 24))
        self.fillButton.setObjectName("fillButton")
        self.currentColorButton = QtWidgets.QPushButton(self.brushPanel)
        self.currentColorButton.setGeometry(QtCore.QRect(10, 430, 41, 41))
        self.currentColorButton.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.currentColorButton.setStyleSheet("background: #fff;")
        self.currentColorButton.setText("")
        self.currentColorButton.setObjectName("currentColorButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(MainWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 25))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vbox = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vbox.setContentsMargins(0, 0, 0, 0)
        self.vbox.setObjectName("vbox")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.currentColorButton.setWhatsThis(
            _translate("MainWindow", "Текущий цвет кисти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
