# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowUI(object):
    def setupUi(self, MainWindowUI):
        MainWindowUI.setObjectName("MainWindowUI")
        MainWindowUI.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindowUI.resize(800, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindowUI.sizePolicy().hasHeightForWidth())
        MainWindowUI.setSizePolicy(sizePolicy)
        MainWindowUI.setMinimumSize(QtCore.QSize(400, 500))
        MainWindowUI.setAutoFillBackground(True)
        MainWindowUI.setStyleSheet("background: #ccc;")
        self.brushPanel = QtWidgets.QGroupBox(MainWindowUI)
        self.brushPanel.setGeometry(QtCore.QRect(0, 0, 115, 500))
        self.brushPanel.setMinimumSize(QtCore.QSize(115, 0))
        self.brushPanel.setMaximumSize(QtCore.QSize(115, 16777215))
        self.brushPanel.setAutoFillBackground(False)
        self.brushPanel.setStyleSheet("QGroupBox {\n"
"    background: #333;\n"
"    border: none;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background: #999;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}")
        self.brushPanel.setTitle("")
        self.brushPanel.setFlat(True)
        self.brushPanel.setCheckable(False)
        self.brushPanel.setObjectName("brushPanel")
        self.penButton = QtWidgets.QPushButton(self.brushPanel)
        self.penButton.setGeometry(QtCore.QRect(10, 10, 42, 42))
        self.penButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.penButton.setStyleSheet("QPushButton {\n"
"    background: #ff00ae;\n"
"}")
        self.penButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/icons/pen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.penButton.setIcon(icon)
        self.penButton.setIconSize(QtCore.QSize(24, 24))
        self.penButton.setFlat(False)
        self.penButton.setObjectName("penButton")
        self.strokeButton = QtWidgets.QPushButton(self.brushPanel)
        self.strokeButton.setGeometry(QtCore.QRect(60, 10, 42, 42))
        self.strokeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.strokeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/icons/stroke.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.strokeButton.setIcon(icon1)
        self.strokeButton.setIconSize(QtCore.QSize(24, 24))
        self.strokeButton.setObjectName("strokeButton")
        self.pickerButton = QtWidgets.QPushButton(self.brushPanel)
        self.pickerButton.setGeometry(QtCore.QRect(10, 60, 42, 42))
        self.pickerButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pickerButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/icons/picker.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pickerButton.setIcon(icon2)
        self.pickerButton.setIconSize(QtCore.QSize(24, 24))
        self.pickerButton.setObjectName("pickerButton")
        self.fillButton = QtWidgets.QPushButton(self.brushPanel)
        self.fillButton.setGeometry(QtCore.QRect(60, 60, 42, 42))
        self.fillButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fillButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("assets/icons/fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fillButton.setIcon(icon3)
        self.fillButton.setIconSize(QtCore.QSize(24, 24))
        self.fillButton.setObjectName("fillButton")

        self.retranslateUi(MainWindowUI)
        QtCore.QMetaObject.connectSlotsByName(MainWindowUI)

    def retranslateUi(self, MainWindowUI):
        _translate = QtCore.QCoreApplication.translate
        MainWindowUI.setWindowTitle(_translate("MainWindowUI", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowUI = QtWidgets.QWidget()
    ui = Ui_MainWindowUI()
    ui.setupUi(MainWindowUI)
    MainWindowUI.show()
    sys.exit(app.exec_())
