# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ResizeSettingsWindow(object):
    def setupUi(self, ResizeSettingsWindow):
        ResizeSettingsWindow.setObjectName("ResizeSettingsWindow")
        ResizeSettingsWindow.resize(380, 150)
        ResizeSettingsWindow.setStyleSheet("QWidget {\n"
"    background: rgb(51, 51, 51);\n"
"    color: white;\n"
"}\n"
"\n"
"QSpinBox {\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 2px 5px;\n"
"    background: #555;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    background: #555;\n"
"    color: white;\n"
"}")
        self.widthBox = QtWidgets.QSpinBox(ResizeSettingsWindow)
        self.widthBox.setGeometry(QtCore.QRect(70, 14, 71, 21))
        self.widthBox.setStyleSheet("")
        self.widthBox.setWrapping(False)
        self.widthBox.setFrame(True)
        self.widthBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.widthBox.setAccelerated(False)
        self.widthBox.setMinimum(1)
        self.widthBox.setMaximum(4096)
        self.widthBox.setProperty("value", 32)
        self.widthBox.setObjectName("widthBox")
        self.cancelButton = QtWidgets.QPushButton(ResizeSettingsWindow)
        self.cancelButton.setGeometry(QtCore.QRect(200, 120, 80, 22))
        self.cancelButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelButton.setObjectName("cancelButton")
        self.okButton = QtWidgets.QPushButton(ResizeSettingsWindow)
        self.okButton.setGeometry(QtCore.QRect(290, 120, 80, 22))
        self.okButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.okButton.setStyleSheet("")
        self.okButton.setObjectName("okButton")
        self.heightBox = QtWidgets.QSpinBox(ResizeSettingsWindow)
        self.heightBox.setGeometry(QtCore.QRect(70, 42, 71, 22))
        self.heightBox.setStyleSheet("")
        self.heightBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.heightBox.setMinimum(1)
        self.heightBox.setMaximum(4096)
        self.heightBox.setProperty("value", 32)
        self.heightBox.setObjectName("heightBox")
        self.label_3 = QtWidgets.QLabel(ResizeSettingsWindow)
        self.label_3.setGeometry(QtCore.QRect(10, 17, 51, 16))
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.keepAspectRatioCheckbox = QtWidgets.QCheckBox(ResizeSettingsWindow)
        self.keepAspectRatioCheckbox.setGeometry(QtCore.QRect(150, 30, 191, 20))
        self.keepAspectRatioCheckbox.setObjectName("keepAspectRatioCheckbox")
        self.label_4 = QtWidgets.QLabel(ResizeSettingsWindow)
        self.label_4.setGeometry(QtCore.QRect(10, 42, 51, 21))
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.scaleCanvasContentCheckbox = QtWidgets.QCheckBox(ResizeSettingsWindow)
        self.scaleCanvasContentCheckbox.setGeometry(QtCore.QRect(10, 70, 211, 21))
        self.scaleCanvasContentCheckbox.setObjectName("scaleCanvasContentCheckbox")
        self.smoothScalingCheckbox = QtWidgets.QCheckBox(ResizeSettingsWindow)
        self.smoothScalingCheckbox.setGeometry(QtCore.QRect(10, 92, 211, 21))
        self.smoothScalingCheckbox.setObjectName("smoothScalingCheckbox")

        self.retranslateUi(ResizeSettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(ResizeSettingsWindow)

    def retranslateUi(self, ResizeSettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        ResizeSettingsWindow.setWindowTitle(_translate("ResizeSettingsWindow", "ResizeSettingsWindow"))
        self.cancelButton.setText(_translate("ResizeSettingsWindow", "Отмена"))
        self.okButton.setText(_translate("ResizeSettingsWindow", "OK"))
        self.label_3.setText(_translate("ResizeSettingsWindow", "Ширина:"))
        self.keepAspectRatioCheckbox.setText(_translate("ResizeSettingsWindow", "Сохранять соотношение сторон"))
        self.label_4.setText(_translate("ResizeSettingsWindow", "Высота:"))
        self.scaleCanvasContentCheckbox.setText(_translate("ResizeSettingsWindow", "Масштабировать содержимое холста"))
        self.smoothScalingCheckbox.setText(_translate("ResizeSettingsWindow", "Сглаженное масштабирование"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ResizeSettingsWindow = QtWidgets.QWidget()
    ui = Ui_ResizeSettingsWindow()
    ui.setupUi(ResizeSettingsWindow)
    ResizeSettingsWindow.show()
    sys.exit(app.exec_())
